pip install bert_score
pip install numpy==1.26.4
pip install rouge-score
pip install scikit-learn
# python compute_scores.py exp/qwen25_omni_sft_newQA/mia_qwen25omni_generation_20_samples_minkpp_all_completion.json &
export CUDA_VISIBLE_DEVICES=0
python compute_scores.py exp/qwen25_omni_sft_newQA_lora_r512_a1024_newdata_all/mia_qwen25omni_generation_10_samples_minkpp_all_origmodel_unseen_1.json &
python compute_scores.py exp/qwen25_omni_sft_newQA_lora_r512_a1024_newdata_all/mia_qwen25omni_generation_10_samples_minkpp_all_origmodel_unseen_2.json &
python compute_scores.py exp/qwen25_omni_sft_newQA_lora_r512_a1024_newdata_all/mia_qwen25omni_generation_10_samples_minkpp_all_origmodel_unseen_3.json &
export CUDA_VISIBLE_DEVICES=1
python compute_scores.py exp/qwen25_omni_sft_newQA_lora_r512_a1024_newdata_all/mia_qwen25omni_generation_10_samples_minkpp_all_origmodel_unseen_4.json &
python compute_scores.py exp/qwen25_omni_sft_newQA_lora_r512_a1024_newdata_all/mia_qwen25omni_generation_10_samples_minkpp_all_origmodel_unseen_5.json &
python compute_scores.py exp/qwen25_omni_sft_newQA_lora_r512_a1024_newdata_all/mia_qwen25omni_generation_10_samples_minkpp_all_origmodel_unseen_6.json &
export CUDA_VISIBLE_DEVICES=2
python compute_scores.py exp/qwen25_omni_sft_newQA_lora_r512_a1024_newdata_all/mia_qwen25omni_generation_10_samples_minkpp_all_origmodel_unseen_7.json &
python compute_scores.py exp/qwen25_omni_sft_newQA_lora_r512_a1024_newdata_all/mia_qwen25omni_generation_10_samples_minkpp_all_origmodel_unseen_8.json &
python compute_scores.py exp/qwen25_omni_sft_newQA_lora_r512_a1024_newdata_all/mia_qwen25omni_generation_10_samples_minkpp_all_origmodel_unseen_9.json &
export CUDA_VISIBLE_DEVICES=3
python compute_scores.py exp/qwen25_omni_sft_newQA_lora_r512_a1024_newdata_all/mia_qwen25omni_generation_10_samples_minkpp_all_origmodel_unseen_10.json &
python compute_scores.py exp/qwen25_omni_sft_newQA_lora_r512_a1024_newdata_all/mia_qwen25omni_generation_10_samples_minkpp_all_origmodel_unseen_11.json &
python compute_scores.py exp/qwen25_omni_sft_newQA_lora_r512_a1024_newdata_all/mia_qwen25omni_generation_10_samples_minkpp_all_origmodel_unseen_12.json &

export CUDA_VISIBLE_DEVICES=4
python compute_scores.py exp/qwen25_omni_sft_newQA_lora_r512_a1024_newdata_all/mia_qwen25omni_generation_10_samples_minkpp_all_unseen_1.json &
python compute_scores.py exp/qwen25_omni_sft_newQA_lora_r512_a1024_newdata_all/mia_qwen25omni_generation_10_samples_minkpp_all_unseen_2.json &
python compute_scores.py exp/qwen25_omni_sft_newQA_lora_r512_a1024_newdata_all/mia_qwen25omni_generation_10_samples_minkpp_all_unseen_3.json &
export CUDA_VISIBLE_DEVICES=5
python compute_scores.py exp/qwen25_omni_sft_newQA_lora_r512_a1024_newdata_all/mia_qwen25omni_generation_10_samples_minkpp_all_unseen_4.json &
python compute_scores.py exp/qwen25_omni_sft_newQA_lora_r512_a1024_newdata_all/mia_qwen25omni_generation_10_samples_minkpp_all_unseen_5.json &
python compute_scores.py exp/qwen25_omni_sft_newQA_lora_r512_a1024_newdata_all/mia_qwen25omni_generation_10_samples_minkpp_all_unseen_6.json &
export CUDA_VISIBLE_DEVICES=6
python compute_scores.py exp/qwen25_omni_sft_newQA_lora_r512_a1024_newdata_all/mia_qwen25omni_generation_10_samples_minkpp_all_unseen_7.json &
python compute_scores.py exp/qwen25_omni_sft_newQA_lora_r512_a1024_newdata_all/mia_qwen25omni_generation_10_samples_minkpp_all_unseen_8.json &
python compute_scores.py exp/qwen25_omni_sft_newQA_lora_r512_a1024_newdata_all/mia_qwen25omni_generation_10_samples_minkpp_all_unseen_9.json &
export CUDA_VISIBLE_DEVICES=7
python compute_scores.py exp/qwen25_omni_sft_newQA_lora_r512_a1024_newdata_all/mia_qwen25omni_generation_10_samples_minkpp_all_unseen_10.json &
python compute_scores.py exp/qwen25_omni_sft_newQA_lora_r512_a1024_newdata_all/mia_qwen25omni_generation_10_samples_minkpp_all_unseen_11.json &
python compute_scores.py exp/qwen25_omni_sft_newQA_lora_r512_a1024_newdata_all/mia_qwen25omni_generation_10_samples_minkpp_all_unseen_12.json &
wait